apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: mycontainer
    image: nginx
    # Specify the secret as part of environment variables
    env:
      - name: HOLY
        valueFrom:
          secretKeyRef:
            name: holy
            key: creditcard
    # Mount the volume as part of the container in the pod
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/diver/hosts
  # Specify the secrets as part of the Pod's specification
  volumes:
  - name: secret-volume
    secret:
      secretName: diver
      defaultMode: 0400
  restartPolicy: Never
  