apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
      - name: HOLY
        valueFrom:
          secretKeyRef:
            name: holy
            key: creditcard
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/diver/hosts
  volumes:
  - name: secret-volume
    secret:
      secretName: diver
      defaultMode: 0400
  restartPolicy: Never
  